### ISSUE TITLE
PSR2 mode fails

### ISSUE THREAD

**Issue by nederdirk** [dericofilho/vim-phpfmt#1]
This plugin fails when PSR2 mode is specified with `g:phpfmt_psr2=1`, because the `--psr2` flag is added after the filename to format, prompting fmt.phar to interpret the flag as a filename.

Actual behavior: `php /home/.../plugin/fmt.phar filename.php --psr2` is executed, resulting in an error.
Expected behavior: `php /home/.../plugin/fmt.phar --psr2 filename.php` is executed.

**Comment by dericofilho** [comment]
Thanks @nederdirk
