### ISSUE TITLE
Question on how to use

### ISSUE THREAD

**Issue by jdanosborne** [dericofilho/vim-phpfmt#3]
Hi, I have installed this plugin through vundle without error but I can't get it to reformat a php file. I type \pcf and nothing happens.

I've probably just misunderstood your instructions but would appreciate some guidance.

Thanks

Dan

**Comment by dericofilho** [comment]
@jdanosborne Hi. I am sorry for this inconvenience. `\pcf` is the right way to invoke the tool.

Please, ensure you have PHP 5.5 or newer installed and that within `.vim/bundle/vim-phpfmt/plugin/phpfmt.vim` you have updated `g:phpfmt_php_path` with PHP full path.

**Comment by jdanosborne** [comment]
Ah OK that will be the problem - I missed that requirement and only have 5.4. I'll see if the hosting company can provide that version.

Thanks,

Dan

**Comment by dericofilho** [comment]
@jdanosborne Why the hosting company? If you are running this on your local Vim, you only need your local PHP to be newer than 5.5

**Comment by jdanosborne** [comment]
I have it working in Sublime text locally but often find myself using vim on the host and then rsyncing back

**Comment by dericofilho** [comment]
@jdanosborne oh I see. It makes sense. Personally, sometimes I use a PHP binary in ~/bin/ so I do not mess with the live one.
