### ISSUE TITLE
:w sets syntax off

### ISSUE THREAD

**Issue by snowiow** [dericofilho/vim-phpfmt#4]
Hi, I got a problem after installing phpfmt via Vundle. If I save a php file, while phpfmt is installed the syntax setting is turned off. As soon as I call pcf, the syntax highlighting is on again. by calling :syntax it also tells me there is no syntax set for this buffer, after executing :w.

**Comment by dericofilho** [comment]
@snowiow  I am really sorry for this bug. Could you please confirm me VIM version and also produce, if possible, a screen recorded session so I can visualize the issue?

**Comment by snowiow** [comment]
Currently I have vim 7.4.729 installed. It happens on gvim and neovim aswell. I don't have anything installed to record my session atm, so I try to explain it with some screenshots, if it's also ok. Otherwise I'll download something. This is the initial view
![initial](https://cloud.githubusercontent.com/assets/3718461/8025717/8ac5c090-0d60-11e5-9e15-6911304ca9b6.png)
After calling :w 
![after_w](https://cloud.githubusercontent.com/assets/3718461/8025721/972c964c-0d60-11e5-9d4a-8263484c908d.png)
After :syntax 
![after_syntax](https://cloud.githubusercontent.com/assets/3718461/8025723/a06dc7e4-0d60-11e5-96ab-cf7b9a649390.png)
After <leader>pcf
![after_pcf](https://cloud.githubusercontent.com/assets/3718461/8025726/a9088830-0d60-11e5-8387-808bbac15fd3.png)

And thx for your fast answer on this issue :)

**Comment by dericofilho** [comment]
@snowiow the screenshots worked just fine. I think I understand the issue. I shall fix it ASAP.

**Comment by snowiow** [comment]
Ok great ty :)

C Cirello <notifications@github.com> schrieb am So., 7. Juni 2015 22:02:

**Comment by dericofilho** [comment]
@snowiow Please, manually update to https://github.com/dericofilho/vim-phpfmt/commit/f976949344dcd36ddff48057fca6601d1e797aba and see if it works.

**Comment by snowiow** [comment]
Tested it on 2 files and it works now :D ty very much for your fast help

**Comment by dericofilho** [comment]
@snowiow thanks for using the plugin.
