### ISSUE TITLE
:w and <leader>pcf kill airline theme

### ISSUE THREAD

**Issue by snowiow** [dericofilho/vim-phpfmt#6]
Hi again,
currently I've got a new problem. Everytime i save or format a file, my airline theme gets killed.
my initial state:
![initial](https://cloud.githubusercontent.com/assets/3718461/8117964/7c60f216-108c-11e5-86ca-070e22dae63b.png)
Then I :w or <leader>pcf:
![grey](https://cloud.githubusercontent.com/assets/3718461/8117976/8b5f7698-108c-11e5-805a-25e093836e4b.png)
Message I got after typing in :g:airline_theme
![msg](https://cloud.githubusercontent.com/assets/3718461/8117987/a290fa62-108c-11e5-9ece-a6b4a21e3c92.png)
Thank you in advance :)

**Comment by dericofilho** [comment]
@snowiow interesting misinteraction. How do I set such configuration on my own vim in order to reproduce this error?

**Comment by snowiow** [comment]
You need the plugin vim-airline(https://github.com/bling/vim-airline). Those are the settings I use for theme and font in my vimrc:
let g:airline_theme = 'light' "set the airline theme
let g:airline_powerline_fonts = 1 "set the appropaite font glyph
That should be everything.

**Comment by dericofilho** [comment]
@snowiow I am not an expert in vim script, and I am tempted to call it incompatible with this plugin. Do you think you can solve this problem? If you open a PR fixing it, I will merge it gladly. Otherwise it might take a while until I fix it, as vim is no my primary editor.

**Comment by snowiow** [comment]
@dericofilho I'm also pretty inexperienced in vim script. I will take a look at it tomorrow, but I don't know if I'm able to solve it.

**Comment by dericofilho** [comment]
@snowiow yeah, let's keep trying.

**Comment by dericofilho** [comment]
@snowiow I just tried to replicate this bug and nothing happened.

Before:
![image](https://cloud.githubusercontent.com/assets/138827/8124236/b2908c2e-10d8-11e5-825d-5b82be55cd70.png)


After:
![image](https://cloud.githubusercontent.com/assets/138827/8124238/b9789f7c-10d8-11e5-8e98-8b5095f50546.png)

**Comment by snowiow** [comment]
Yes, the code highlighting stays the same. It's about the statusbar at the bottom of my editor, which looses it's theme.

**Comment by dericofilho** [comment]
how do I active this?

**Comment by snowiow** [comment]
It should be activated by default after you installed it(https://github.com/bling/vim-airline#installation). I did it via Vundle.

**Comment by snowiow** [comment]
Hi, I found out that the problem is this line:
https://github.com/dericofilho/vim-phpfmt/blob/master/plugin/phpfmt.vim#L55
Because Airline overwrites the standard statusbar and this overwrites it again.
Now you could just call :AirlineRefresh if airline is installed, after that call, but then the msg won't be seen at all by airline users. Now I tried to print it as a msg in the ex line instead(like the msg, which comes up when you have written to a file). I tried it with various echo commands, but I always have to press enter manually afterwards, what is pretty annoying. Do you know a way to bypass this issue and would this be a solution at all for you?

**Comment by dericofilho** [comment]
@snowiow why not remove the line?

**Comment by snowiow** [comment]
Would also be a solution, but I thought you wanted to have some feedback if that procedure went through sucessfully.

**Comment by dericofilho** [comment]
@snowiow Well, it is pretty easy to see if it worked or not because the buffer gets updated. I would remove the line.

**Comment by snowiow** [comment]
Ok, good :)

**Comment by dericofilho** [comment]
@snowiow could you please open a PR with it?

**Comment by snowiow** [comment]
resolved f976949
