### ISSUE TITLE
Turning off autoaligning the import statements

### ISSUE THREAD

**Issue by snowiow** [dericofilho/vim-phpfmt#8]
Hey there, 
this time I only have a question. Is it possible to turn off the auto alignment of the imports(use, require)? 

Thank you in advance.

**Comment by dericofilho** [comment]
yes. Tweak `fmt.phar` incantation with `--exclude=OrderUseClauses,SortUseNameSpace` It will disable the feature you requested.

**Comment by snowiow** [comment]
ok ty. it worked :) 
One more question, where do I find all these options for fmt.phar like OrderUseClauses, SortUseNameSpace?

**Comment by dericofilho** [comment]
Run `fmt.phar --list` it shows all possible additional steps. Also, you can use `export FMTDEBUG="step"` to see which step is changing you don't want, and put accordingly in `--exclude`.
